'use strict';var Lf=function(a){this.uE="number"==typeof a?0<a?1:0>a?-1:null:null==a?null:a?-1:1};Lf.prototype.zU=function(a,b){var c=0,e=0,f=!1;a=xe(a,b).split(Be);for(b=0;b<a.length;b++){var g=a[b];ze.test(xe(g,void 0))?(c++,e++):Ae.test(g)?f=!0:ye.test(xe(g,void 0))?e++:Ce.test(g)&&(f=!0)}return 0==e?f?1:0:.4<c/e?-1:1};Lf.prototype.VT=function(a,b){return this.o1(this.zU(a,b))};Lf.prototype.o1=function(a){return-1==(0==a?this.uE:a)?"rtl":"ltr"};
Lf.prototype.mark=function(){switch(this.uE){case 1:return"\u200e";case -1:return"\u200f";default:return""}};if("undefined"!=typeof angular){var Mf=angular.module("chrome_18n",[]);chrome.runtime&&chrome.runtime.getManifest&&chrome.runtime.getManifest().default_locale&&Mf.directive("angularMessage",function(){return{restrict:"E",replace:!0,controller:["$scope",function(a){var b=this;this.Tv=this.Jn=null;a.dirForText=function(a){b.Jn||(b.Jn=chrome.i18n.getMessage("@@bidi_dir")||"ltr");b.Tv||(b.Tv=new Lf("rtl"==b.Jn));return b.Tv.VT(a||"")}}],compile:function(a,b){b=b.key;var c=null,e=document.createElement("amr");
b&&!b.match(/^\d+$/)&&(b=chrome.i18n.getMessage(b),null==b&&e.setAttribute("id","missing"));if(b){var f=chrome.i18n.getMessage(b+"_ph"),c=[];if(null!=f)for(c=f.split("\ue000"),f=0;f<c.length;++f)c[f]=c[f].replace(/^{{(.*)}}$/,'<amrp dir="{{dirForText($1)}}">{{$1}}</amrp>');c=chrome.i18n.getMessage(b,c)}else e.setAttribute("r","nokey");c?e.innerHTML=c:(e.setAttribute("tl","false"),e.innerHTML=a.html());a.replaceWith(e)}}})};var Nf=/^[\w+/]+[=]{0,2}$/;var Of=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var e=c||h,f=e.document,g;g=(g=(g=(e||h).document.querySelector("script[nonce]"))&&g.getAttribute("nonce"))&&Nf.test(g)?g:void 0;g&&(a.nonce=g);if("help"==a.flow){var k=ma("document.location.href",e);!a.helpCenterContext&&k&&(a.helpCenterContext=k.substring(0,1200));k=!0;if(b&&JSON&&JSON.stringify){var p=JSON.stringify(b);(k=1200>=p.length)&&(a.psdJson=p)}k||(b={invalidPsd:!0})}b=[a,b,c];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||
"//www.google.com/tools/feedback";if(k=e.GOOGLE_FEEDBACK_START)k.apply(e,b);else{var e=c+"/load.js?",q;for(q in a)b=a[q],null!=b&&!ta(b)&&(e+=encodeURIComponent(q)+"="+encodeURIComponent(b)+"&");a=f.createElement("script");g&&a.setAttribute("nonce",g);a.src=e;f.body.appendChild(a)}};m("userfeedback.api.startFeedback",Of,void 0);var Pf=function(){this.PE=this.RD=this.receiverVersion=this.modelName=this.IJ=this.Cr=this.Xs=""};var Qf=chrome.i18n.getMessage("4163185390680253103"),Rf=chrome.i18n.getMessage("492097680647953484"),Sf=chrome.i18n.getMessage("2575016469622936324"),Tf=chrome.i18n.getMessage("128276876460319075"),Uf=chrome.i18n.getMessage("3326722026796849289"),Vf=chrome.i18n.getMessage("1018984561488520517"),Wf=chrome.i18n.getMessage("8205999658352447129"),Xf=chrome.i18n.getMessage("5723583529370342957"),Yf=chrome.i18n.getMessage("1550904064710828958"),Zf=chrome.i18n.getMessage("5014364904504073524"),$f=chrome.i18n.getMessage("2194670894476780934"),
ag=chrome.i18n.getMessage("6614468912728530636"),bg=chrome.i18n.getMessage("5910595154486533449"),cg=chrome.i18n.getMessage("5363086287710390513"),dg=chrome.i18n.getMessage("244647017322945605"),eg=chrome.i18n.getMessage("5375576275991472719"),fg=chrome.i18n.getMessage("4592127349908255218"),gg=chrome.i18n.getMessage("843316808366399491"),hg=chrome.i18n.getMessage("5699813974548050528"),ig=chrome.i18n.getMessage("8515148417333877999"),jg=chrome.i18n.getMessage("1636686747687494376"),kg=chrome.i18n.getMessage("4148300086676792937"),
lg=chrome.i18n.getMessage("3219866268410307919"),mg=chrome.i18n.getMessage("9211708838274008657"),og=chrome.i18n.getMessage("8706273405040403641"),pg=chrome.i18n.getMessage("4756056595565370923"),qg=chrome.i18n.getMessage("7876724262035435114"),rg=chrome.i18n.getMessage("5485620192329479690"),sg=chrome.i18n.getMessage("6963873398546068901"),tg=chrome.i18n.getMessage("3567591856726172993"),ug=chrome.i18n.getMessage("3239956785410157548");var vg=function(a,b){var c=this;this.RE=b;this.o=a;this.o.top=a;this.lF=[];this.uC=!1;this.ce=new Pf;this.Laa();this.Eaa();this.Faa();this.Gaa();this.Iaa();this.NU=Qa();this.o.userEmail="";chrome.identity.getProfileUserInfo(function(a){c.o.userEmail=a.email;c.yp()});this.o.yourAnswerText=ug;this.o.language=chrome.i18n&&chrome.i18n.getUILanguage?chrome.i18n.getUILanguage():chrome.runtime.getManifest().default_locale;this.o.requestLogsInProgress=!1};d=vg.prototype;
d.Eaa=function(){this.lF=[{value:"Bug",desc:Qf},{value:"FeatureRequest",desc:Rf},{value:"MirroringQuality",desc:Sf},{value:"Discovery",desc:Tf},{value:"Other",desc:Uf}];this.o.feedbackTypes=this.lF};d.QB=function(a){for(var b=[],c=1;c<arguments.length;c++)b.push(new wg(c,arguments[c]));b.push(new wg(0,arguments[0]));return b};
d.Laa=function(){this.o.videoSmoothnessRatings=this.QB($f,Vf,Wf,Xf,Yf,Zf);this.o.videoQualityRatings=this.QB($f,ag,bg,cg,dg,eg);this.o.audioQualityRatings=this.QB($f,fg,gg,hg,ig,jg)};d.Faa=function(){this.o.includeFineLogs=!0;this.o.feedbackType="Bug";this.o.sendFeedback=this.Z7.bind(this);this.o.cancel=this.rS.bind(this);this.o.attachLogsClick=this.uD.bind(this);this.o.viewLogs=this.Dca.bind(this)};
d.Gaa=function(){this.o.$watchGroup("videoSmoothness videoQuality audioQuality feedbackDescription comments feedbackType".split(" "),this.IS.bind(this));this.o.sufficientFeedback=!1};d.Iaa=function(){this.o.$watch("attachLogs",this.uD.bind(this));this.o.attachLogs=!0};d.rS=function(){this.o.feedbackDescription&&!confirm(kg)||window.close()};
d.IS=function(){var a=this.o.feedbackType;this.o.sufficientFeedback="MirroringQuality"==a?this.o.videoSmoothness||this.o.videoQuality||this.o.audioQuality||this.o.comments:"Discovery"==a?this.o.visibleInSetup||this.o.comments:!!this.o.feedbackDescription};
d.Z7=function(){if(this.o.sufficientFeedback){var a=this.o.feedbackType,b="";"MirroringQuality"==a?(this.o.videoSmoothness&&(b+="\nVideo Smoothness: "+this.o.videoSmoothness),this.o.videoQuality&&(b+="\nVideo Quality: "+this.o.videoQuality),this.o.audioQuality&&(b+="\nAudio: "+this.o.audioQuality),this.o.projectedContentUrl&&(b+="\nProjected Content/URL: "+this.o.projectedContentUrl),this.o.comments&&(b+="\nComments: "+this.o.comments)):"Discovery"==a?(this.o.visibleInSetup&&(b+="\nChromecast Visible in Setup: "+
this.o.visibleInSetup),this.o.hasNetworkSoftware&&(b+="\nUsing VPN/proxy/firewall/NAS Software: "+this.o.hasNetworkSoftware),this.o.networkDescription&&(b+="\nNetwork Description: "+this.o.networkDescription),this.o.comments&&(b+="\nComments: "+this.o.comments)):b=this.o.feedbackDescription;this.Y7("Type: "+a+"\n\n"+b)}};
d.Y7=function(a){this.o.sendDialogText=lg;this.o.okButton=tg;this.o.feedbackSent=!1;this.RE.show({locals:{zla:this.o.feedbackSent,Bra:this.o.sendDialogText,x2:this.o.okButton},scope:this.o,preserveScope:!0,bindToController:!0,template:'<md-dialog id="feedback-confirmation"><md-dialog-content><div id="send-feedback-text">{{sendDialogText}}</div><md-dialog-actions><md-button class="md-raised md-primary"ng-disabled="!feedbackSent" ng-click="closeWindow()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',
controller:this.lv});this.PL(a,Date.now())};d.PL=function(a,b){var c=Date.now();!this.o.requestLogsInProgress||5E3<c-b?this.hU(a):setTimeout(this.PL.bind(this),1E3,a,b)};
d.hU=function(a){var b=this,c=0,e=function(a,c,e){e?a(!0):(b.o.sendDialogText=pg,b.yp(),c(Error("Failed to send")))},f=chrome.declarativeWebRequest?"MrTeamfood":"MRStable";(new te(function(){c++;return new Promise(function(c,k){var g=b.o.userEmail,q=b.ce;c=e.bind(null,c,k);k=chrome.runtime.getManifest();Of({productId:85561,bucket:f,flow:"submit",serverUri:"https://www.google.com/tools/feedback",allowNonLoggedInFeedback:!0,locale:k.default_locale,enableAnonymousFeedback:!g,report:{description:a},callback:c},
{version:k.version,description:k.description,user_email:g||"NA",logs:q.Xs||"NA",external_logs:q.Cr||"NA",device_model:q.modelName||"NA",receiver_version:q.receiverVersion||"NA",dash_report_url:q.IJ||"NA",cast_device_counts:q.RD,dial_device_counts:q.PE})})},1E4,4)).bu(2).start().then(function(){b.o.sendDialogText=og;b.o.feedbackSent=!0;b.yp()},function(){b.o.sendDialogText=mg;b.o.feedbackSent=!0;b.yp()})};
d.uD=function(){var a=this;this.ce=new Pf;this.o.attachLogs&&(this.o.requestLogsInProgress=!0,chrome.runtime.sendMessage(new Ff(this.NU,"retrieve_log_data"),function(b){a.o.requestLogsInProgress=!1;a.ce.Xs=b.logs||"no extension";b.castStreamingLogs&&(a.ce.IJ=b.castStreamingLogs);b.castDeviceCounts&&(a.ce.RD=b.castDeviceCounts);b.dialDeviceCounts&&(a.ce.PE=b.dialDeviceCounts);if(b=b.device)if(b.model&&(a.ce.modelName=b.model),b.version&&(a.ce.receiverVersion=b.version),!a.uC){var c=Qa();a.uC=!0;a.ce.Cr=
If(b.ip,c,a.Q3.bind(a))}}))};
d.Dca=function(){this.o.logs=this.ce.Xs;this.o.logsHeader=qg;this.o.sendLogs=rg;this.o.fineLogsWarning=sg;this.o.okButton=tg;this.RE.show({locals:{kia:this.o.attachLogs,Xs:this.o.logs,Rma:this.o.includeFineLogs,Mna:this.o.logsHeader,Dra:this.o.sendLogs,Bla:this.o.fineLogsWarning,x2:this.o.okButton},scope:this.o,preserveScope:!0,bindToController:!0,clickOutsideToClose:!0,template:'<md-dialog><md-dialog-content id="logs-dialog"><div class="subheading">{{logsHeader}}</div><div ng-show="includeFineLogs && attachLogs"id="feedback-fine-log-warning" class="informative">{{fineLogsWarning}}</div><pre>{{logs}}</pre><div class="send-logs"><md-checkbox type="checkbox" ng-model="attachLogs"ng-change="attachLogsClick()"><span>{{sendLogs}}</span></md-checkbox></div><md-dialog-actions><md-button class="md-raised md-primary"ng-click="closeDialog()">{{okButton}}</md-button></md-dialog-actions></md-dialog-content></md-dialog>',controller:this.lv})};
d.Q3=function(a,b){this.uC=!1;this.ce.Cr="error"==a?"":b;this.o.attachLogs||(this.ce.Cr="");this.yp()};d.yp=function(){this.o.$$phase||this.o.$apply()};d.lv=function(a,b){a.closeWindow=function(){window.close()};a.closeDialog=function(){b.hide()}};vg.prototype.lv.$inject=["$scope","$mdDialog"];var wg=function(a,b){this.id=a;this.desc=b;this.text=0==a?b:a+" ("+b+")"};
angular.module("feedbackApp","chrome_18n material.components.button material.components.checkbox material.components.dialog material.components.input material.components.radioButton".split(" ")).controller("FeedbackCtrl",["$scope","$mdDialog",vg]);m("ng.safehtml.googSceHelper.isGoogHtmlType",function(a){return a&&a.wl?!0:!1},void 0);m("ng.safehtml.googSceHelper.isCOMPILED",function(){return!0},void 0);m("ng.safehtml.googSceHelper.unwrapAny",function(a){if(a instanceof Qe)return Re(a);if(a instanceof Te)return Ue(a);if(a instanceof Ne)return Oe(a);if(a instanceof Ke)return Le(a);if(a instanceof He)return Ie(a);throw Error();},void 0);
m("ng.safehtml.googSceHelper.unwrapGivenContext",function(a,b){if("html"==a)return Ue(b);if("resourceUrl"==a||"templateUrl"==a)return Re(b);if("url"==a)return b instanceof Qe?Re(b):Oe(b);if("css"==a)return Le(b);if("js"==a)return Ie(b);throw Error();},void 0);
