'use strict';var mo={TAB:0,EC:1,RP:2},no=function(a){Tg("MediaRouter.CastStreaming.Start.Success",a,mo)};var oo=C("mr.mirror.cast.LogUploader"),qo=function(a,b,c){po("raw_events.log.gz",a,b,c);return b?"https://crash.corp.google.com/samples?stbtiq="+b:""},po=function(a,b,c,e){if(0==b.size)oo.info("Trying to upload an empty file to Crash"),e&&e(null);else{var f=new FormData;f.append("prod","Cast");f.append("ver",chrome.runtime.getManifest().version);f.append(a,b);c&&f.append("comments",c);Bf("https://clients2.google.com/cr/report",function(a){a=a.target;var b=null;a.Xd()?(b=a.Pi(),oo.info("Upload to Crash succeeded: "+
b)):oo.info("Upload to Crash failed. HTTP status: "+a.Qa());e&&e(b)},"POST",f,void 0,3E4)}};var ro=function(){this.Io=0;Ih(this)},to=function(){so||(so=new ro);return so};ro.prototype.H9=function(a){this.Io=a};ro.prototype.Naa=function(){var a={fraction:.01,autoSubmitTimeLimitMillis:6048E5},b=a.autoSubmitTimeLimitMillis,c=Date.now();return this.Io&&b&&c-this.Io<b?!1:Math.random()<a.fraction};
var vo=function(a,b,c,e){var f=new uo;f.extVersion=chrome.runtime.getManifest().version;f.extChannel="public";f.minBitrate=c.minVideoBitrate;f.maxBitrate=c.maxVideoBitrate;f.resolution=c.maxWidth+"x"+c.maxHeight;f.minResolution=c.minWidth+"x"+c.minHeight;if(f.minResolution==f.resolution)f.resolutionChangePolicy="fixed";else if(c.senderSideLetterboxing){var g=c.TG();f.minResolution+=" (altered to: "+g.width+"x"+g.height+")";f.resolutionChangePolicy="fixed-aspect-ratio"}else f.resolutionChangePolicy=
"variable";f.maxFrameRate=c.maxFrameRate;f.minLatency=c.minLatencyMillis;f.maxLatency=c.maxLatencyMillis;f.animatedLatency=c.animatedLatencyMillis;f.useDscp=c.dscpEnabled;f.useTdls=c.useTdls;null!=b&&(f.receiverVersion=b);null!=a&&(f.receiverProductName=a);e.length&&(f.receiverStatusData=e);return f},xo=function(a,b,c,e,f){wo.info("getRawEvents");return new Promise(function(g,k){var p=function(b){wo.info("Got receiver version: "+b);b=JSON.stringify(vo(c,b,e,f));chrome.cast.streaming.rtpStream.getRawEvents(a,
b,g)};"Chromecast"==c?Kf(b).then(p,k):p(null)})},yo=function(a,b,c,e){wo.info("getStats");return new Promise(function(f,g){var k=function(b){wo.info("Got receiver version: "+b);var g=vo(c,b,e,[]);chrome.cast.streaming.rtpStream.getStats(a,function(a){var b={tags:g};Kb(b,a);f(b)})};"Chromecast"==c?Kf(b).then(k,g):k(null)})};ro.prototype.oa=function(){return"mirror.cast.LogUtils"};ro.prototype.getData=function(){return[void 0,{lastAutoSubmitMillis:this.Io}]};
ro.prototype.Wa=function(){var a=Gh(this);this.Io=a&&a.lastAutoSubmitMillis||0};var so=null,wo=C("mr.mirror.cast.LogUtils"),uo=function(){this.ext="MR";this.senderProductName="Google Chrome";this.senderVersion=Tj;this.senderPlatform=$b;this.senderUserAgent=Lb||""};var zo=function(a){return a&&a.getAudioTracks()&&0<a.getAudioTracks().length?a.getAudioTracks()[0]:null},Ao=function(a){return a&&a.getVideoTracks()&&0<a.getVideoTracks().length?a.getVideoTracks()[0]:null};var Bo=C("mr.NetworkUtils"),Co=function(a,b){return Hg?new Promise(function(c,e){chrome.networkingPrivate.setWifiTDLSEnabledState(a,b,function(a){chrome.runtime.lastError?(Bo.l("Unable to set TDLS state: state = "+b+", error = "+chrome.runtime.lastError.message),e("Unable to set TDLS state to "+b+".")):(Bo.info("TDLS state changed: state = "+b+", status = "+a),c(a))})}):Promise.reject("TDLS feature not enabled.")};var Do={bga:"OFFER",qda:"ANSWER",tga:"PRESENTATION",Fea:"GET_STATUS",cha:"STATUS_RESPONSE",Eea:"GET_CAPABILITIES",Kda:"CAPABILITIES_RESPONSE"};var Eo=function(a,b){this.sessionId=a;this.seqNum=b;this.type="PRESENTATION"};var Fo=function(){this.capabilities=this.status=this.Ze=this.error=this.result=this.type=this.seqNum=this.sessionId=null},Io=function(a){var b;try{if("string"!==typeof a)throw SyntaxError("Cannot parse non-string as JSON");var c;Go(JSON.parse(a),function(a){c=Ho(a)},function(){throw Error("non-Object result from JSON parse");});return c}catch(e){b=e instanceof SyntaxError?"JSON parse error: "+e.message:"Type coercion error: "+e.message}"string"==typeof a?a="a string: "+a:a instanceof ArrayBuffer?
(a=new Uint8Array(a),a="an ArrayBuffer whose base64 is "+btoa(String.fromCharCode.apply(null,a))):a="of invalid data type "+typeof a;throw Error(b+". Input was "+a);},Ho=function(a){var b=new Fo;null!=a.sessionId&&(b.sessionId=String(a.sessionId));Jo(a.seqNum,function(a){b.seqNum=a},function(){throw Error('"seqNum" must be a number');});if("type"in a){for(var c=String(a.type).toUpperCase(),e=ia(Object.keys(Do)),f=e.next();!f.done;f=e.next())if(Do[f.value]==c){b.type=c;break}if(!b.type)throw Error('not a known message "type"');
}"result"in a&&(b.result=String(a.result));Go(a.error,function(a){b.error=Ko(a)},function(){throw Error('"error" must be an Object');});Go(a.answer,function(a){b.Ze=Lo(a)},function(){throw Error('"answer" must be an Object');});Go(a.status,function(a){b.status=Mo(a)},function(){throw Error('"status" must be an Object');});"capabilities"in a||!("mediaCaps"in a||"keySystems"in a)||(a.capabilities={},"mediaCaps"in a&&(a.capabilities.mediaCaps=a.mediaCaps),"keySystems"in a&&(a.capabilities.keySystems=
a.keySystems));Go(a.capabilities,function(a){b.capabilities=No(a)},function(){throw Error('"capabilities" must be an Object');});return b},Go=function(a,b,c){void 0!==a&&(a instanceof Object?b(a):c())},Jo=function(a,b,c){void 0!==a&&("number"!==typeof a?c():b(a))},Oo=function(a,b,c){void 0!==a&&(a instanceof Array&&a.every(function(a){return"number"===typeof a})?b(a):c())},Po=function(a,b,c){void 0!==a&&(a instanceof Array?b(a.map(function(a){return String(a)})):c())},Qo=function(){this.SB=null;this.RL=
[];this.Tp=[];this.wS=this.YK=this.CP=null},Lo=function(a){var b=new Qo;Jo(a.udpPort,function(a){b.SB=a},function(){throw Error('"answer.udpPort" must be a number');});Oo(a.sendIndexes,function(a){b.RL=a},function(){throw Error('"answer.sendIndexes" must be an array of numbers');});Oo(a.ssrcs,function(a){b.Tp=a},function(){throw Error('"answer.ssrcs" must be an array of numbers');});"IV"in a&&(b.CP=String(a.IV));"receiverGetStatus"in a&&(b.YK="true"==String(a.receiverGetStatus).toLowerCase());"castMode"in
a&&(b.wS=String(a.castMode));return b},Ro=function(){this.details=this.description=this.code=null},Ko=function(a){var b=new Ro;Jo(a.code,function(a){b.code=a},function(){throw Error('"error.code" must be a number');});"description"in a&&(b.description=String(a.description));Go(a.details,function(a){b.details=a},function(){throw Error('"error.details" must be an Object');});return b},So=function(){this.kC=this.jC=null},Mo=function(a){var b=new So;Jo(a.wifiSnr,function(a){b.jC=a},function(){throw Error('"status.wifiSnr" must be a number');
});Oo(a.wifiSpeed,function(a){b.kC=a},function(){throw Error('"status.wifiSpeed" must be an array of numbers');});return b},To=function(){this.n1=this.Z1=null},No=function(a){var b=new To;Po(a.mediaCaps,function(a){b.Z1=a},function(){throw Error('"capabilities.mediaCaps" must be an array');});if("keySystems"in a){a=a.keySystems;if(!(a instanceof Array))throw Error('"capabilities.keySystems" must be an array');b.n1=a.map(function(a){var b;Go(a,function(a){b=Uo(a)},function(){throw Error('"capabilities.keySystems" entries must be *Objects');
});return b})}return b},Vo=function(){this.bU=this.t5=this.s5=this.r5=this.Cca=this.wR=this.Q7=this.XS=this.initDataTypes=this.m1=null},Uo=function(a){var b=new Vo;"keySystemName"in a&&(b.m1=String(a.keySystemName));Po(a.initDataTypes,function(a){b.initDataTypes=a},function(){throw Error('"capabilities.initDataTypes" must be an array');});Po(a.codecs,function(a){b.XS=a},function(){throw Error('"capabilities.codecs" must be an array');});Po(a.secureCodecs,function(a){b.Q7=a},function(){throw Error('"capabilities.secureCodecs" must be an array');
});Po(a.audioRobustness,function(a){b.wR=a},function(){throw Error('"capabilities.audioRobustness" must be an array');});Po(a.videoRobustness,function(a){b.Cca=a},function(){throw Error('"capabilities.videoRobustness" must be an array');});"persistentLicenseSessionSupport"in a&&(b.r5=String(a.persistentLicenseSessionSupport));"persistentReleaseMessageSessionSupport"in a&&(b.s5=String(a.persistentReleaseMessageSessionSupport));"persistentStateSupport"in a&&(b.t5=String(a.persistentStateSupport));"distinctiveIdentifierSupport"in
a&&(b.bU=String(a.distinctiveIdentifierSupport));return b};var Wo=function(a,b){this.address=a;this.port=b},Xo=function(a,b,c){uh.call(this,b);this.a=C("mr.mirror.cast.Session");this.Ea=a;this.Lc=xg.$r(b.id);this.C=b.Fe.sessionId;this.ee=new Wo(b.Fe.IN,2344);this.It=b.Fe.JN;this.Sc=null;this.si=!1;this.fc=null;this.mk=!1;this.hi=0;this.va=this.Aq=this.Bq=null;this.C5=["H264","VP8"];this.oy=new Map;this.xD=null;this.GL=u(this.Z3,this);this.FL=u(this.Y3,this);this.qo=null;this.np=new Ci(30);this.ZK=!1;this.hk=c||null;this.MA=new Xh("mirror.cast.SeqNumGenerator");
this.$c=this.yf=null;this.lz=0};ja(Xo,uh);d=Xo.prototype;d.start=function(a){var b=this,c=zo(a);a=Ao(a);this.yf=new Kg("MediaRouter.CastStreaming.Session.Launch");this.va=new zc;this.x0();this.Ea.useTdls&&Co(this.ee.address,!0).then(function(a){"Connected"!=a&&(b.Ea.useTdls=!1)},function(){b.Ea.useTdls=!1});chrome.cast.streaming.session.create(c,a,function(a,c,g){b.Sc=a;b.fc=c;b.hi=g;b.Lc.onMessage=u(b.tt,b);b.lz=0;b.LA({type:"OFFER",sessionId:b.getId(),seqNum:b.MA.ds(),offer:b.zn()})});return this.va.promise};
d.stop=function(){this.$c&&(this.$c.end(),this.$c=null);this.a.info("Stopping "+this.getId());null!==this.Sc&&(chrome.cast.streaming.rtpStream.stop(this.Sc),chrome.cast.streaming.rtpStream.destroy(this.Sc),this.Sc=null,this.si=!1);null!==this.fc&&(chrome.cast.streaming.rtpStream.stop(this.fc),chrome.cast.streaming.rtpStream.destroy(this.fc),this.fc=null,this.mk=!1);this.hi&&(chrome.cast.streaming.udpTransport.destroy(this.hi),this.hi=0);this.Ea.useTdls&&Co(this.ee.address,!1);this.va&&(this.va.resolve(this),
this.va=null);chrome.cast.streaming.rtpStream.onStarted.removeListener(this.GL);chrome.cast.streaming.rtpStream.onError.removeListener(this.FL);null!==this.qo&&(window.clearTimeout(this.qo),this.qo=null);this.Bq=this.Aq=null;if(this.hk&&this.hk.onSessionStop)this.hk.onSessionStop(this.ee);this.Lc.Pa();return Promise.resolve()};d.P9=function(a){this.si&&chrome.cast.streaming.rtpStream.toggleLogging(this.Sc,a);this.mk&&chrome.cast.streaming.rtpStream.toggleLogging(this.fc,a)};
d.getLogs=function(){var a=this;if(!this.si&&!this.mk)return Promise.reject(Error("No streams has been started yet."));var b=[];if(this.si){var c=xo(this.Sc,this.ee.address,this.It,this.Ea,this.np.H());b.push(c)}this.mk&&(c=xo(this.fc,this.ee.address,this.It,this.Ea,this.np.H()),b.push(c));return Promise.all(b).then(function(b){b=new Blob(b,{type:"application/gzip"});a.a.info("Events blob size: "+b.size);return b})};
d.getStats=function(){var a=[];if(this.si){var b=yo(this.Sc,this.ee.address,this.It,this.Ea);a.push(b)}this.mk&&(b=yo(this.fc,this.ee.address,this.It,this.Ea),a.push(b));this.np.V()&&a.push(Promise.resolve({receiverStatusData:this.np.H()}));return Promise.all(a).then(function(a){var b={};a.forEach(function(a){Kb(b,a)});return b})};
d.mT=function(){var a=chrome.cast.streaming.rtpStream.getSupportedParams(this.Sc)[0];a.payload.channels=2;a.payload.maxBitrate=this.Ea.audioBitrate;a.payload.maxFrameRate=100;a.payload.maxLatency=this.Ea.maxLatencyMillis;a.payload.minLatency=this.Ea.minLatencyMillis;a.payload.animatedLatency=this.Ea.animatedLatencyMillis;a.payload.ssrc=Math.floor(499999*Math.random())+1;a.payload.clockRate=48E3;a.payload.feedbackSsrc=2;a.payload.payloadType=127;a.payload.aesKey=this.Bq;a.payload.aesIvMask=this.Aq;
return a};
d.DT=function(){var a=this,b=[];if(null===this.fc)return b;var c=chrome.cast.streaming.rtpStream.getSupportedParams(this.fc);this.C5.forEach(function(e){var f=c.find(function(a){return a.payload.codecName.toLowerCase()==e.toLowerCase()});f&&(f.payload.maxFrameRate=a.Ea.maxFrameRate,f.payload.minBitrate=a.Ea.minVideoBitrate,f.payload.maxBitrate=a.Ea.maxVideoBitrate,f.payload.maxLatency=a.Ea.maxLatencyMillis,f.payload.minLatency=a.Ea.minLatencyMillis,f.payload.animatedLatency=a.Ea.animatedLatencyMillis,f.payload.aesKey=
a.Bq,f.payload.aesIvMask=a.Aq,f.payload.ssrc=Math.floor(499999*Math.random())+500001,f.payload.feedbackSsrc=12,f.payload.payloadType=96,b.push(f))});return b};
d.zn=function(){var a=this,b=0,c=[];if(this.Sc){var e=this.mT();this.xD=e;e={index:b,type:"audio_source",codecName:e.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:e.payload.payloadType,ssrc:e.payload.ssrc,targetDelay:this.Ea.animatedLatencyMillis,aesKey:e.payload.aesKey,aesIvMask:e.payload.aesIvMask,bitRate:0<e.payload.maxBitrate?1E3*e.payload.maxBitrate:60*e.payload.maxFrameRate+e.payload.clockRate*e.payload.channels,sampleRate:e.payload.clockRate,timeBase:"1/"+e.payload.clockRate,
channels:e.payload.channels,rtpExtensions:["adaptive_playout_delay"]};this.Ea.enableLogging&&Kb(e,{receiverRtcpEventLog:!0});this.Ea.dscpEnabled&&Kb(e,{receiverRtcpDscp:46});c.push(e);b++}this.DT().forEach(function(e){var f={index:b,type:"video_source",codecName:e.payload.codecName.toLowerCase(),rtpProfile:"cast",rtpPayloadType:e.payload.payloadType,ssrc:e.payload.ssrc,targetDelay:a.Ea.animatedLatencyMillis,aesKey:e.payload.aesKey,aesIvMask:e.payload.aesIvMask,maxFrameRate:Math.round(1E3*e.payload.maxFrameRate)+
"/1000",timeBase:"1/90000",maxBitRate:e.payload.maxBitrate,resolutions:[{width:a.Ea.maxWidth,height:a.Ea.maxHeight}],rtpExtensions:["adaptive_playout_delay"]};a.Ea.enableLogging&&Kb(f,{receiverRtcpEventLog:!0});a.Ea.dscpEnabled&&Kb(f,{receiverRtcpDscp:46});c.push(f);a.oy.set(b,e);b++});return{supportedStreams:c}};
d.Z3=function(a){a==this.Sc?this.si=!0:a==this.fc&&(this.mk=!0);this.si&&(null===this.fc||this.mk)&&(this.P9(this.Ea.enableLogging),this.va&&(this.va.resolve(this),this.va=null));this.$c=new Pg("MediaRouter.CastStreaming.Session.Length")};d.Y3=function(a,b){if(a==this.Sc)this.a.l("Audio stream error "+b);else if(a==this.fc)this.a.l("Video stream error "+b);else{this.a.l("Error for stream "+a+": "+b);return}this.va&&(this.va.reject(Error("Error for stream "+a+": "+b)),this.va=null);this.stop()};
d.iba=function(a,b){var c=this;this.a.v(function(){return"Starting streaming ... "+JSON.stringify({udpTransportId:c.hi,receiverIpEndPoint:c.ee,"audio ID":c.Sc,"video ID":c.fc,"audio params":a,"video params":b})});if(sa(chrome.cast.streaming.udpTransport.setOptions)){var e={};this.Ea.dscpEnabled&&(this.a.info("Enable DSCP in sender."),e.DSCP=!0);chrome.cast.streaming.udpTransport.setOptions(this.hi,e)}chrome.cast.streaming.udpTransport.setDestination(this.hi,{address:this.ee.address,port:this.ee.port});
chrome.cast.streaming.rtpStream.onStarted.addListener(this.GL);chrome.cast.streaming.rtpStream.onError.addListener(this.FL);a&&chrome.cast.streaming.rtpStream.start(this.Sc,a);b&&chrome.cast.streaming.rtpStream.start(this.fc,b)};
d.tt=function(a){var b=this;if("urn:x-cast:com.google.cast.webrtc"==a.namespace_){var c,e=null;try{c=Io(a.data)}catch(k){c=new Fo,e=k.message}if("ANSWER"==c.type)if("ok"==c.result&&c.Ze){c.Ze.SB&&(this.ee.port=c.Ze.SB);this.ZK=!!c.Ze.YK;if(this.hk)this.hk.onAnswer(this.ee);this.yf&&(this.yf.end(),this.yf=null);this.a.info("Starting streaming");var f=this.xD,g=null;c.Ze.RL.forEach(function(a){f&&0==a?c.Ze.Tp[a]&&(f.payload.feedbackSsrc=c.Ze.Tp[a]):b.oy.has(a)&&(g?b.a.l("Receiver selected multiple video stream"):
(g=b.oy.get(a),c.Ze.Tp[a]&&(g.payload.feedbackSsrc=c.Ze.Tp[a])))});null!==this.fc&&null===g&&(this.a.l("Receiver is capable of video, but did not specify a video stream index in the ANSWER message."),chrome.cast.streaming.rtpStream.destroy(this.fc),this.fc=null);if(f||g)this.fH(),this.iba(f,g),this.va&&(this.va.resolve(this),this.va=null)}else this.va&&(this.va.reject(Error("Non-OK answer received: "+JSON.stringify(c))),this.va=null),this.stop();else"STATUS_RESPONSE"==c.type&&c.status?(a={},null!=
c.status.jC&&(a.wifiSnr=c.status.jC),null!=c.status.kC&&(a.wifiSpeed=c.status.kC.pop()),e={},e[(new Date).toISOString()]=a,this.np.add(e)):(e||(e="Ignoring message: "+JSON.stringify(c)),10>this.lz?this.a.l(e):this.a.v(e),++this.lz)}};d.x0=function(){this.Aq=Yh(window.crypto.getRandomValues(new Uint8Array(16)));this.Bq=Yh(window.crypto.getRandomValues(new Uint8Array(16)))};d.TL=function(){this.LA(this.HY())};d.LA=function(a){this.Lc.sendMessage(a,{namespace:"urn:x-cast:com.google.cast.webrtc"})};
d.fH=function(){this.qo=null;this.hi&&this.ZK&&(this.LA({type:"GET_STATUS",sessionId:this.getId(),seqNum:this.MA.ds(),get_status:["wifiSnr","wifiSpeed"]}),this.qo=window.setTimeout(u(this.fH,this),12E4))};d.HY=function(){var a=new Eo(this.C,this.MA.ds());a.title=this.pA||void 0;a.icons=this.iconUrl&&!this.Cs?[new chrome.cast.Image(this.iconUrl)]:[];return a};d.getId=function(){return this.C};var Yo=function(){sh.call(this,"cast_streaming");this.hk=null};ja(Yo,sh);d=Yo.prototype;d.getName=function(){return"cast_streaming"};d.jr=function(a,b){return new Xo(a,b,this.hk)};d.Nt=function(){no(0)};d.Jt=function(){no(1)};d.jA=function(){no(2)};d.Kt=function(){Sg("MediaRouter.CastStreaming.Session.End")};d.Lt=function(a){Tg("MediaRouter.CastStreaming.Start.Failure",a,Vg)};d.Mt=function(){Sg("MediaRouter.CastStreaming.Stream.End")};
d.Qv=function(a){var b=this,c=a.getLogs().then(function(a){return a},function(a){b.m.l("Get cast streaming logs failed.",a)});a=a.getStats().then(function(a){return a},function(a){b.m.l("Get cast streaming stats failed.",a)});var e=new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)});return Promise.all([c,a,e]).then(function(a){var c=ia(a);a=c.next().value;var e=c.next().value,c=c.next().value;if(a){var f=new FileReader;f.onloadend=function(){Ph("mr.temp.mirror.cast.Service.mirrorLogs",
f.result)};f.readAsBinaryString(a)}c&&(a&&to().Naa()?qo(a,void 0,b.J2.bind(b)):e&&po("stats.json",new Blob([JSON.stringify(e)],{type:"application/json"}),void 0,void 0))})};d.J2=function(a){a&&to().H9(Date.now())};d.Fg=function(a){var b=this;this.m.info("Received message to upload logs for "+a);return this.Ga?this.Ga.getLogs().then(function(b){return qo(b,a)},function(c){b.m.l("Get cast streaming logs failed.",c);return b.zJ(a)}):Promise.resolve(this.zJ(a))};
d.zJ=function(a){var b=window.localStorage["mr.temp.mirror.cast.Service.mirrorLogs"];if(!b)return"";window.localStorage.removeItem("mr.temp.mirror.cast.Service.mirrorLogs");this.m.info("Uploading saved logs for feedback.");for(var c=new Uint8Array(b.length),e=0;e<c.length;e++)c[e]=b.charCodeAt(e);return qo(new Blob([c],{type:"application/gzip"}),a)};var Zo=new Yo;qh("mr.mirror.cast.Service",Zo);
